language: bash
sudo: required

git:
  depth: 1

matrix:
  include:
    - os: linux
      dist: bionic # ubuntu 18.04
    - os: linux
      dist: focal # ubuntu 20.04

env:
  global:
    - WG_SCRIPT_DISABLE_REBOOT=on

install:
  # enable ipv6
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0

script:
  - sudo ${TRAVIS_BUILD_DIR}/wg-ubuntu-server-up.sh
